ALTER TABLE "billing_payment_records" ADD COLUMN "created_by" uuid;--> statement-breakpoint
ALTER TABLE "billing_payment_records" ADD COLUMN "updated_by" uuid;--> statement-breakpoint
ALTER TABLE "subscriptions" ADD COLUMN "created_by" uuid;--> statement-breakpoint
ALTER TABLE "subscriptions" ADD COLUMN "updated_by" uuid;--> statement-breakpoint
ALTER TABLE "usage_metrics" ADD COLUMN "created_by" uuid;--> statement-breakpoint
ALTER TABLE "usage_metrics" ADD COLUMN "updated_by" uuid;--> statement-breakpoint
ALTER TABLE "roles" ADD COLUMN "created_by" uuid;--> statement-breakpoint
ALTER TABLE "roles" ADD COLUMN "updated_by" uuid;--> statement-breakpoint
ALTER TABLE "sys_dictionaries" ADD COLUMN "created_by" uuid;--> statement-breakpoint
ALTER TABLE "sys_dictionaries" ADD COLUMN "updated_by" uuid;--> statement-breakpoint
ALTER TABLE "tenants" ADD COLUMN "created_by" uuid;--> statement-breakpoint
ALTER TABLE "tenants" ADD COLUMN "updated_by" uuid;--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "created_by" uuid;--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "updated_by" uuid;--> statement-breakpoint
ALTER TABLE "market_channels" ADD COLUMN "created_by" uuid;--> statement-breakpoint
ALTER TABLE "market_channels" ADD COLUMN "updated_by" uuid;--> statement-breakpoint
ALTER TABLE "product_attribute_templates" ADD COLUMN "created_by" uuid;--> statement-breakpoint
ALTER TABLE "product_attribute_templates" ADD COLUMN "updated_by" uuid;--> statement-breakpoint
ALTER TABLE "product_templates" ADD COLUMN "created_by" uuid;--> statement-breakpoint
ALTER TABLE "product_templates" ADD COLUMN "updated_by" uuid;--> statement-breakpoint
ALTER TABLE "customer_merge_logs" ADD COLUMN "created_by" uuid;--> statement-breakpoint
ALTER TABLE "customer_merge_logs" ADD COLUMN "updated_by" uuid;--> statement-breakpoint
ALTER TABLE "phone_view_logs" ADD COLUMN "created_by" uuid;--> statement-breakpoint
ALTER TABLE "phone_view_logs" ADD COLUMN "updated_by" uuid;--> statement-breakpoint
ALTER TABLE "customer_addresses" ADD COLUMN "created_by" uuid;--> statement-breakpoint
ALTER TABLE "customer_addresses" ADD COLUMN "updated_by" uuid;--> statement-breakpoint
ALTER TABLE "channel_categories" ADD COLUMN "created_by" uuid;--> statement-breakpoint
ALTER TABLE "channel_categories" ADD COLUMN "updated_by" uuid;--> statement-breakpoint
ALTER TABLE "quote_items" ADD COLUMN "created_by" uuid;--> statement-breakpoint
ALTER TABLE "quote_items" ADD COLUMN "updated_by" uuid;--> statement-breakpoint
ALTER TABLE "quote_plan_items" ADD COLUMN "created_by" uuid;--> statement-breakpoint
ALTER TABLE "quote_plan_items" ADD COLUMN "updated_by" uuid;--> statement-breakpoint
ALTER TABLE "quote_plans" ADD COLUMN "created_by" uuid;--> statement-breakpoint
ALTER TABLE "quote_plans" ADD COLUMN "updated_by" uuid;--> statement-breakpoint
ALTER TABLE "quote_rooms" ADD COLUMN "created_by" uuid;--> statement-breakpoint
ALTER TABLE "quote_rooms" ADD COLUMN "updated_by" uuid;--> statement-breakpoint
ALTER TABLE "quote_template_items" ADD COLUMN "created_by" uuid;--> statement-breakpoint
ALTER TABLE "quote_template_items" ADD COLUMN "updated_by" uuid;--> statement-breakpoint
ALTER TABLE "quote_template_rooms" ADD COLUMN "created_by" uuid;--> statement-breakpoint
ALTER TABLE "quote_template_rooms" ADD COLUMN "updated_by" uuid;--> statement-breakpoint
ALTER TABLE "order_changes" ADD COLUMN "created_by" uuid;--> statement-breakpoint
ALTER TABLE "order_changes" ADD COLUMN "updated_by" uuid;--> statement-breakpoint
ALTER TABLE "channel_discount_overrides" ADD COLUMN "created_by" uuid;--> statement-breakpoint
ALTER TABLE "channel_discount_overrides" ADD COLUMN "updated_by" uuid;--> statement-breakpoint
ALTER TABLE "channel_specific_prices" ADD COLUMN "created_by" uuid;--> statement-breakpoint
ALTER TABLE "channel_specific_prices" ADD COLUMN "updated_by" uuid;--> statement-breakpoint
ALTER TABLE "fabric_inventory" ADD COLUMN "created_by" uuid;--> statement-breakpoint
ALTER TABLE "fabric_inventory" ADD COLUMN "updated_by" uuid;--> statement-breakpoint
ALTER TABLE "package_products" ADD COLUMN "created_by" uuid;--> statement-breakpoint
ALTER TABLE "package_products" ADD COLUMN "updated_by" uuid;--> statement-breakpoint
ALTER TABLE "product_bundle_items" ADD COLUMN "created_by" uuid;--> statement-breakpoint
ALTER TABLE "product_bundle_items" ADD COLUMN "updated_by" uuid;--> statement-breakpoint
ALTER TABLE "product_bundles" ADD COLUMN "created_by" uuid;--> statement-breakpoint
ALTER TABLE "product_bundles" ADD COLUMN "updated_by" uuid;--> statement-breakpoint
ALTER TABLE "product_packages" ADD COLUMN "created_by" uuid;--> statement-breakpoint
ALTER TABLE "product_packages" ADD COLUMN "updated_by" uuid;--> statement-breakpoint
ALTER TABLE "product_suppliers" ADD COLUMN "created_by" uuid;--> statement-breakpoint
ALTER TABLE "product_suppliers" ADD COLUMN "updated_by" uuid;--> statement-breakpoint
ALTER TABLE "production_tasks" ADD COLUMN "created_by" uuid;--> statement-breakpoint
ALTER TABLE "production_tasks" ADD COLUMN "updated_by" uuid;--> statement-breakpoint
ALTER TABLE "purchase_order_items" ADD COLUMN "created_by" uuid;--> statement-breakpoint
ALTER TABLE "purchase_order_items" ADD COLUMN "updated_by" uuid;--> statement-breakpoint
ALTER TABLE "work_order_items" ADD COLUMN "created_by" uuid;--> statement-breakpoint
ALTER TABLE "work_order_items" ADD COLUMN "updated_by" uuid;--> statement-breakpoint
ALTER TABLE "install_items" ADD COLUMN "created_by" uuid;--> statement-breakpoint
ALTER TABLE "install_items" ADD COLUMN "updated_by" uuid;--> statement-breakpoint
ALTER TABLE "install_photos" ADD COLUMN "created_by" uuid;--> statement-breakpoint
ALTER TABLE "install_photos" ADD COLUMN "updated_by" uuid;--> statement-breakpoint
ALTER TABLE "install_tasks" ADD COLUMN "created_by" uuid;--> statement-breakpoint
ALTER TABLE "install_tasks" ADD COLUMN "updated_by" uuid;--> statement-breakpoint
ALTER TABLE "measure_items" ADD COLUMN "created_by" uuid;--> statement-breakpoint
ALTER TABLE "measure_items" ADD COLUMN "updated_by" uuid;--> statement-breakpoint
ALTER TABLE "measure_sheets" ADD COLUMN "created_by" uuid;--> statement-breakpoint
ALTER TABLE "measure_sheets" ADD COLUMN "updated_by" uuid;--> statement-breakpoint
ALTER TABLE "measure_tasks" ADD COLUMN "created_by" uuid;--> statement-breakpoint
ALTER TABLE "measure_tasks" ADD COLUMN "updated_by" uuid;--> statement-breakpoint
ALTER TABLE "account_transactions" ADD COLUMN "created_by" uuid;--> statement-breakpoint
ALTER TABLE "account_transactions" ADD COLUMN "updated_by" uuid;--> statement-breakpoint
ALTER TABLE "accounting_periods" ADD COLUMN "created_by" uuid;--> statement-breakpoint
ALTER TABLE "accounting_periods" ADD COLUMN "updated_by" uuid;--> statement-breakpoint
ALTER TABLE "ap_labor_fee_details" ADD COLUMN "created_by" uuid;--> statement-breakpoint
ALTER TABLE "ap_labor_fee_details" ADD COLUMN "updated_by" uuid;--> statement-breakpoint
ALTER TABLE "ap_labor_statements" ADD COLUMN "created_by" uuid;--> statement-breakpoint
ALTER TABLE "ap_labor_statements" ADD COLUMN "updated_by" uuid;--> statement-breakpoint
ALTER TABLE "ap_supplier_statements" ADD COLUMN "created_by" uuid;--> statement-breakpoint
ALTER TABLE "ap_supplier_statements" ADD COLUMN "updated_by" uuid;--> statement-breakpoint
ALTER TABLE "ar_statements" ADD COLUMN "created_by" uuid;--> statement-breakpoint
ALTER TABLE "ar_statements" ADD COLUMN "updated_by" uuid;--> statement-breakpoint
ALTER TABLE "chart_of_accounts" ADD COLUMN "created_by" uuid;--> statement-breakpoint
ALTER TABLE "chart_of_accounts" ADD COLUMN "updated_by" uuid;--> statement-breakpoint
ALTER TABLE "commission_records" ADD COLUMN "created_by" uuid;--> statement-breakpoint
ALTER TABLE "commission_records" ADD COLUMN "updated_by" uuid;--> statement-breakpoint
ALTER TABLE "finance_accounts" ADD COLUMN "created_by" uuid;--> statement-breakpoint
ALTER TABLE "finance_accounts" ADD COLUMN "updated_by" uuid;--> statement-breakpoint
ALTER TABLE "finance_audit_logs" ADD COLUMN "created_by" uuid;--> statement-breakpoint
ALTER TABLE "finance_audit_logs" ADD COLUMN "updated_by" uuid;--> statement-breakpoint
ALTER TABLE "finance_configs" ADD COLUMN "created_by" uuid;--> statement-breakpoint
ALTER TABLE "finance_configs" ADD COLUMN "updated_by" uuid;--> statement-breakpoint
ALTER TABLE "payment_bill_items" ADD COLUMN "created_by" uuid;--> statement-breakpoint
ALTER TABLE "payment_bill_items" ADD COLUMN "updated_by" uuid;--> statement-breakpoint
ALTER TABLE "payment_bills" ADD COLUMN "created_by" uuid;--> statement-breakpoint
ALTER TABLE "payment_bills" ADD COLUMN "updated_by" uuid;--> statement-breakpoint
ALTER TABLE "payment_order_items" ADD COLUMN "created_by" uuid;--> statement-breakpoint
ALTER TABLE "payment_order_items" ADD COLUMN "updated_by" uuid;--> statement-breakpoint
ALTER TABLE "payment_plan_nodes" ADD COLUMN "created_by" uuid;--> statement-breakpoint
ALTER TABLE "payment_plan_nodes" ADD COLUMN "updated_by" uuid;--> statement-breakpoint
ALTER TABLE "receipt_bill_items" ADD COLUMN "created_by" uuid;--> statement-breakpoint
ALTER TABLE "receipt_bill_items" ADD COLUMN "updated_by" uuid;--> statement-breakpoint
ALTER TABLE "reconciliation_details" ADD COLUMN "created_by" uuid;--> statement-breakpoint
ALTER TABLE "reconciliation_details" ADD COLUMN "updated_by" uuid;--> statement-breakpoint
ALTER TABLE "reconciliations" ADD COLUMN "created_by" uuid;--> statement-breakpoint
ALTER TABLE "reconciliations" ADD COLUMN "updated_by" uuid;--> statement-breakpoint
ALTER TABLE "statement_confirmation_details" ADD COLUMN "created_by" uuid;--> statement-breakpoint
ALTER TABLE "statement_confirmation_details" ADD COLUMN "updated_by" uuid;--> statement-breakpoint
ALTER TABLE "voucher_templates" ADD COLUMN "created_by" uuid;--> statement-breakpoint
ALTER TABLE "voucher_templates" ADD COLUMN "updated_by" uuid;--> statement-breakpoint
ALTER TABLE "approval_delegations" ADD COLUMN "created_by" uuid;--> statement-breakpoint
ALTER TABLE "approval_delegations" ADD COLUMN "updated_by" uuid;--> statement-breakpoint
ALTER TABLE "approval_flows" ADD COLUMN "created_by" uuid;--> statement-breakpoint
ALTER TABLE "approval_flows" ADD COLUMN "updated_by" uuid;--> statement-breakpoint
ALTER TABLE "approval_nodes" ADD COLUMN "created_by" uuid;--> statement-breakpoint
ALTER TABLE "approval_nodes" ADD COLUMN "updated_by" uuid;--> statement-breakpoint
ALTER TABLE "approval_tasks" ADD COLUMN "created_by" uuid;--> statement-breakpoint
ALTER TABLE "approval_tasks" ADD COLUMN "updated_by" uuid;--> statement-breakpoint
ALTER TABLE "approvals" ADD COLUMN "created_by" uuid;--> statement-breakpoint
ALTER TABLE "approvals" ADD COLUMN "updated_by" uuid;--> statement-breakpoint
ALTER TABLE "debt_ledgers" ADD COLUMN "created_by" uuid;--> statement-breakpoint
ALTER TABLE "debt_ledgers" ADD COLUMN "updated_by" uuid;--> statement-breakpoint
ALTER TABLE "liability_notices" ADD COLUMN "created_by" uuid;--> statement-breakpoint
ALTER TABLE "liability_notices" ADD COLUMN "updated_by" uuid;--> statement-breakpoint
ALTER TABLE "audit_logs" ADD COLUMN "created_by" uuid;--> statement-breakpoint
ALTER TABLE "audit_logs" ADD COLUMN "updated_by" uuid;--> statement-breakpoint
ALTER TABLE "notification_queue" ADD COLUMN "created_by" uuid;--> statement-breakpoint
ALTER TABLE "notification_queue" ADD COLUMN "updated_by" uuid;--> statement-breakpoint
ALTER TABLE "notification_templates" ADD COLUMN "created_by" uuid;--> statement-breakpoint
ALTER TABLE "notification_templates" ADD COLUMN "updated_by" uuid;--> statement-breakpoint
ALTER TABLE "notifications" ADD COLUMN "created_by" uuid;--> statement-breakpoint
ALTER TABLE "notifications" ADD COLUMN "updated_by" uuid;--> statement-breakpoint
ALTER TABLE "loyalty_transactions" ADD COLUMN "updated_by" uuid;--> statement-breakpoint
ALTER TABLE "inventory_logs" ADD COLUMN "created_by" uuid;--> statement-breakpoint
ALTER TABLE "inventory_logs" ADD COLUMN "updated_by" uuid;--> statement-breakpoint
ALTER TABLE "warehouses" ADD COLUMN "created_by" uuid;--> statement-breakpoint
ALTER TABLE "warehouses" ADD COLUMN "updated_by" uuid;--> statement-breakpoint
ALTER TABLE "verification_codes" ADD COLUMN "created_by" uuid;--> statement-breakpoint
ALTER TABLE "verification_codes" ADD COLUMN "updated_by" uuid;--> statement-breakpoint
ALTER TABLE "sales_targets" ADD COLUMN "created_by" uuid;--> statement-breakpoint
ALTER TABLE "sales_annual_targets" ADD COLUMN "created_by" uuid;--> statement-breakpoint
ALTER TABLE "sales_weekly_targets" ADD COLUMN "created_by" uuid;--> statement-breakpoint
ALTER TABLE "labor_rates" ADD COLUMN "created_by" uuid;--> statement-breakpoint
ALTER TABLE "labor_rates" ADD COLUMN "updated_by" uuid;--> statement-breakpoint
ALTER TABLE "worker_skills" ADD COLUMN "created_by" uuid;--> statement-breakpoint
ALTER TABLE "worker_skills" ADD COLUMN "updated_by" uuid;--> statement-breakpoint
ALTER TABLE "invitations" ADD COLUMN "created_by" uuid;--> statement-breakpoint
ALTER TABLE "invitations" ADD COLUMN "updated_by" uuid;--> statement-breakpoint
ALTER TABLE "showroom_shares" ADD COLUMN "created_by" uuid;--> statement-breakpoint
ALTER TABLE "showroom_shares" ADD COLUMN "updated_by" uuid;--> statement-breakpoint
ALTER TABLE "tenant_profiles" ADD COLUMN "created_by" uuid;--> statement-breakpoint
ALTER TABLE "tenant_profiles" ADD COLUMN "updated_by" uuid;--> statement-breakpoint
ALTER TABLE "landing_testimonials" ADD COLUMN "created_by" uuid;--> statement-breakpoint
ALTER TABLE "landing_testimonials" ADD COLUMN "updated_by" uuid;--> statement-breakpoint
ALTER TABLE "order_batch_links" ADD COLUMN "created_by" uuid;--> statement-breakpoint
ALTER TABLE "order_batch_links" ADD COLUMN "updated_by" uuid;