/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Category of the product.
         * @enum {string}
         */
        ProductCategory: "curtain" | "wallcovering" | "background-wall" | "window-cushion" | "standard-product";
        /**
         * @description Lifecycle status of an Order.
         * @enum {string}
         */
        OrderStatus: "pending_measurement" | "measuring_pending_assignment" | "measuring_assigned" | "measuring_pending_visit" | "measuring_pending_confirmation" | "pending_design" | "pending_review" | "pending_quote" | "pending_deposit" | "pending_production" | "in_production" | "pending_delivery" | "pending_installation" | "completed" | "cancelled";
        User: {
            /** @description Unique identifier. */
            id: number;
            /** Format: email */
            email: string;
            name: string;
            phone?: string;
            /** @description Role of the user (e.g., admin, sales, designer). */
            role: string;
            avatar?: string | null;
            status?: string | null;
        };
        Lead: {
            /** Format: uuid */
            id: string;
            lead_number?: string | null;
            name: string;
            phone: string;
            status: string;
            customer_level?: string;
            project_address?: string | null;
            /** @description ID of the user this lead is assigned to. */
            assigned_to_id?: number | null;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        LeadDetail: {
            id?: string;
            leadNumber?: string;
            customerName?: string;
            projectAddress?: string;
            phone?: string;
            requirements?: string[];
            budgetMin?: number;
            budgetMax?: number;
            /** @enum {string} */
            customerLevel?: "A" | "B" | "C" | "D";
            status?: string;
            businessTags?: string[];
            appointmentTime?: string;
            /** @enum {string|null} */
            appointmentReminder?: "48h" | "24h" | null;
            currentOwner?: {
                name?: string;
                avatar?: string;
            };
            designer?: {
                name?: string;
                avatar?: string;
            };
            shoppingGuide?: {
                name?: string;
                avatar?: string;
            };
            createdAt?: string;
            lastFollowUpAt?: string;
            source?: string;
            quoteVersions?: number;
            constructionProgress?: string;
            expectedPurchaseDate?: string;
            expectedCheckInDate?: string;
            areaSize?: number;
            quoteDetails?: {
                currentVersion?: number;
                versions?: {
                    version?: number;
                    quoteNo?: string;
                    totalAmount?: number;
                    status?: string;
                }[];
            };
            measurementCompleted?: boolean;
            installationCompleted?: boolean;
            financialStatus?: string;
            expectedMeasurementDate?: string;
            expectedInstallationDate?: string;
            totalQuoteAmount?: number;
            isCancelled?: boolean;
            isPaused?: boolean;
        };
        Order: {
            id: number;
            order_number: string;
            customer_id: number;
            sales_id: number;
            /** Format: uuid */
            lead_id?: string | null;
            status: components["schemas"]["OrderStatus"];
            total_amount: number;
            paid_amount?: number;
            /** Format: date-time */
            order_date?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        CurtainItem: {
            id?: string;
            space?: string;
            product?: string;
            imageUrl?: string;
            packageTag?: string;
            isPackageItem?: boolean;
            /** @enum {string} */
            packageType?: "cloth" | "gauze" | "track";
            unit?: string;
            width?: number;
            height?: number;
            quantity?: number;
            unitPrice?: number;
            usageAmount?: number;
            amount?: number;
            priceDifference?: number;
            differenceAmount?: number;
            remark?: string;
        };
        OrderFormData: {
            leadId?: string;
            leadNumber?: string;
            customerName?: string;
            customerPhone?: string;
            projectAddress?: string;
            designer?: string;
            salesPerson?: string;
            createTime?: string;
            expectedDeliveryTime?: string;
            spacePackages?: {
                [key: string]: string;
            };
            packageUsage?: {
                cloth?: number;
                gauze?: number;
                track?: number;
            };
            curtains?: components["schemas"]["CurtainItem"][];
            wallcoverings?: components["schemas"]["CurtainItem"][];
            backgroundWalls?: components["schemas"]["CurtainItem"][];
            windowCushions?: components["schemas"]["CurtainItem"][];
            standardProducts?: components["schemas"]["CurtainItem"][];
            items?: components["schemas"]["CurtainItem"][];
            subtotals?: {
                [key: string]: number;
            };
            packageAmount?: number;
            packageExcessAmount?: number;
            upgradeAmount?: number;
            totalAmount?: number;
        };
        OrderItem: {
            category?: components["schemas"]["ProductCategory"];
            productName?: string;
            quantity?: number;
            unitPrice?: number;
            totalPrice?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
